---
- hosts: nodes
  become: yes
  become_user: root
  tasks:
    - name: install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Install pre-req
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools 
          - sos
          - psacct
          - bash-completion
          - kexec-tools
        state: present
    - name: Update Centos kernel
      yum:
        name: "*"
        state: latest
    
    - name: Install Docker
      yum:
        name:
           - docker
        state: present
    
    - name: disable SElinux
      command: setenforce 0
      ignore_errors: yes
    
    - name: disable SELinux on reboot
      selinux:
        state: disabled
      ignore_errors: yes
    
    - name: ensure IPv4 forwarding set to 1
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      ignore_errors: yes
    
    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
    
    - name: install kubelet
      yum:
        name: kubelet-1.17.0
        state: present
        update_cache: true
    
    - name: install kubeadm
      yum:
        name: kubeadm-1.17.0
        state: present
    
    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started
      
    - name: Make sure a docker is running
      systemd:
        state: started
        name: docker
    
    - name: wait for 10 seconds
      pause:
        seconds: 10

    - name: Rebooting
      reboot: