---
- hosts: bastions
  tasks:
    - name: create deployment
      k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/config/deployment.yml') | from_yaml }}"
    
    - name: create service
      k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/config/service.yml') | from_yaml }}"