---
- hosts: bastions
  become: yes
  become_user: root
  tasks:
    - name: create kubeconfig dir
      file:
        path: /var/lib/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

- hosts: masters
  become: yes
  become_user: root
  tasks:
    
    - name: fetch kubeconfig 
      fetch:
        src: /root/.kube/config
        dest: "/var/lib/jenkins/.kube/config"
        flat: yes
    
- hosts: bastions
  become: yes
  become_user: root
  tasks:
    
    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: Change onwership
      file:
        path: /var/lib/jenkins/.kube/config
        owner: jenkins
        group: jenkins
        mode: '0744'

    - name: install kubectl
      yum:
        name: kubectl-1.17.0
        state: present
        allow_downgrade: yes
